### ISSUE TITLE
[EXTRA 0.5d] Allow issues to exist outside of a board if they're mentioned in an epic

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/github-issue-janitor#6]
As an engineeing team, we'd like the janitor to only consider an issue as "orphaned" and put it in the triage column if it's *neither* mentioned in the text of an issue labelled "epic" or "theme", nor in a project board, so we can support managing technical debt and ops issues through epics on the product board.

## Open Questions

How hard is it to tell if an issue is mentioned in an epic? We'll need to read the `Body` string field of all the issues of type epic/theme (see `Labels` field of issue type) and parse the Markdown for things that look like issue URLs (or direct #XYZ refs inside the same repo?) and build a what-references-what graph. See https://godoc.org/github.com/google/go-github/github#Issue

## ACs

- [x] As long as an issue is mentioned in an epic, we can drop it from any boards and it won't come back into Triage.
- [x] An issue in an epic that is also in the current sprint board will not be interfered with by the janitor.
- [x] Issues in epics that are also in a board OTHER than the current sprint board might be a mistake, but there's valid reasons to do that, so they also shouldn't be interefered with. The janitor MAY identify such issues and explicitly do nothing about them if it's convenient to do so, so we have a place to hook behaviour onto in future.

**Comment by alaric-dotmesh** [comment]
Done in janitor v0.1.0
